### ISSUE TITLE
Number of members mismatch in title

### ISSUE THREAD

**Issue by lgrcia** [borisghidaglia/meet-hn#1]
The number of members reported in the title of a given city often mismatches with the actual number of members in the list. For New York, 3 members are in the list but 7 reported in the title.

<img width="571" alt="Screenshot 2024-09-14 at 11 53 08" src="https://github.com/user-attachments/assets/ea7f2dbc-944f-4b59-a668-331f626e0deb">

See also:
- https://meet.hn/city/us-Fort-Collins
- https://meet.hn/city/us-Los-Angeles

**Comment by borisghidaglia** [comment]
Hey @lgrcia 👋, thanks for reporting! 

A cache issue _(which I resolved on launch day)_ was partly responsible for this. 
I initially thought it was the sole cause until I read this and realized the Los Angeles hacker count is still incorrect.

I'm in the process of gathering all the feedbacks hackers made since launch day. 
Adding this to the list!

**Comment by borisghidaglia** [comment]
Should finally be fixed with the commit: https://github.com/borisghidaglia/meet-hn/commit/c2aa78b960027c26146c86fadc331efe4767bed5

Don't hesitate to re-open if you notice it again somewhere 🙏
