### ISSUE TITLE
HN post feedback

### ISSUE THREAD

**Issue by vasnt** [borisghidaglia/meet-hn#5]
https://news.ycombinator.com/item?id=41539125

There may be many good feedback, are you planning to transfer/compile them on "github projects" https://github.com/borisghidaglia/meet-hn/projects

or on roadmap?

**Comment by borisghidaglia** [comment]
Hey, thanks for sharing!

I'm actually in the process of gathering all the feedbacks hackers made since launch day.

Today I do this on notion. I don't think I'll be opening a Github project.
But I'll be sharing fixes and new features on [meet_hn](https://x.com/meet_hn), which I'll retweet from my account [borisfyi](https://x.com/borisfyi). 
I see you are a twitter user and that you follow me, so you shouldn't miss any updates!

**Comment by borisghidaglia** [comment]
A lot of the feedbacks have been implemented since! 
Feel free to open another issue if you would like to suggest something else, or to send a feedback at [meet.hn/feedback](https://meet.hn/feedback)
