### ISSUE TITLE
Missing link prefix in Socials after clicking the autofill button

### ISSUE THREAD

**Issue by reynaldichernando** [borisghidaglia/meet-hn#6]
## Summary
<img width="513" alt="image" src="https://github.com/user-attachments/assets/c04c90d6-5efd-4182-8355-af9807f73cc6">

## How to Reproduce
1. Add socials, with the corresponding values
2. Save/Add me on the map
3. Reopen meet.hn and click the 👋 (autofill) button

**Comment by borisghidaglia** [comment]
Hey @reynaldichernando, thanks for reporting 🙏

That's a good catch! 
I had never tried to click the button with the data filled already.
There are actually other problems with the autofill feature (for example if you type my username: `sirobg` and click autofill again, some of your info persist). It's likely a problem with React keys/state that I messed up somehow. 

I'm in the process of gathering all the feedbacks hackers made since launch day.
Adding this to the list!

**Comment by reynaldichernando** [comment]
Hi @borisghidaglia, thank you for the reply 👍 
If the project is open for contribution, I would like to work on the issue I mentioned!

**Comment by borisghidaglia** [comment]
Of course, please go ahead! 

But please be aware that I might not review your PR very fast, as this pb is more of an edge case than most problems occurring today (like the cities with diacritics not loading properly or the inability to select a given city if its name exists several times in a country, for example).

Does it still work for you?

**Comment by reynaldichernando** [comment]
Got it, I have created the PR for fixing my issue.
Regarding the other issues about cities with diacritics or name existing several times, I haven't tried it yet, but I'll see if I can reproduce it and try to help with the issue.

**Comment by borisghidaglia** [comment]
Fixed. Explanation in a related PR comment: https://github.com/borisghidaglia/meet-hn/pull/10#issuecomment-2400664678
